version: '3'

services:
  app:
    build: .
    image: spring-boot-tomcat-img
    ports:
      - 8080:8080
    networks:
      - simple-app-mysql
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
#    ports:
#      - "5432:5432"
    networks:
      - simple-app-mysql
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  simple-app-mysql: